name: cms
services:
  cms_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Logitar.Cms_mssql
    restart: unless-stopped
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: tB5H47dWCqE6G9TZ
    ports:
      - 1440:1433
    volumes:
      - mssql_backup:/var/opt/mssql/backup
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log

  cms_postgres:
    image: postgres
    container_name: Logitar.Cms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: z8hk7RfBFuJY3tXV
    ports:
      - 5440:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cms_backend:
    build:
      context: ./backend
      dockerfile: /src/Logitar.Cms/Dockerfile
    image: cms_backend
    container_name: Logitar.Cms_backend
    depends_on:
      - cms_mssql
      - cms_postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
      POSTGRESQLCONNSTR_Cms: "User ID=postgres;Password=z8hk7RfBFuJY3tXV;Host=cms_postgres;Port=5432;Database=cms;"
      SQLCONNSTR_Cms: "Server=cms_mssql;Database=Cms;User Id=SA;Password=tB5H47dWCqE6G9TZ;Persist Security Info=False;Encrypt=False;"
    ports:
      - 8090:8080

volumes:
  mssql_backup:
  mssql_data:
  mssql_log:
  postgres_data:
