name: cms
services:
  cms_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Logitar.Cms_mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: hMe5CJmF2SVLDtvN
    ports:
      - 1440:1433

  cms_postgres:
    image: postgres
    container_name: Logitar.Cms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: kzXnZxLf9s8WQ3vh
    ports:
      - 5440:5432
