name: cms
services:
  cms_mongo:
    image: mongo
    container_name: Logitar.Cms_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: cms
      MONGO_INITDB_ROOT_PASSWORD: PbsBwp2TM9Fy5A6g
    ports:
      - 27030:27017

  cms_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Logitar.Cms_mssql
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: hMe5CJmF2SVLDtvN
    ports:
      - 1440:1433

  cms_postgres:
    image: postgres
    container_name: Logitar.Cms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: kzXnZxLf9s8WQ3vh
    ports:
      - 5440:5432

  cms_backend:
    build:
      context: ./backend
      dockerfile: /src/Logitar.Cms/Dockerfile
    image: cms_backend
    container_name: Logitar.Cms_backend
    depends_on:
      - cms_mongo
      - cms_mssql
      - cms_postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
      MongoDB:ConnectionString: mongodb://cms:PbsBwp2TM9Fy5A6g@cms_mongo:27017/
      POSTGRESQLCONNSTR_Cms: "User ID=postgres;Password=kzXnZxLf9s8WQ3vh;Host=cms_postgres;Port=5432;Database=Cms;"
      SQLCONNSTR_Cms: "Server=cms_mssql;Database=Cms;User Id=SA;Password=hMe5CJmF2SVLDtvN;Persist Security Info=False;Encrypt=False;"
    ports:
      - 8090:8080
