// <auto-generated />
using Logitar.Cms.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logitar.Cms.EntityFrameworkCore.SqlServer.Migrations
{
  [DbContext(typeof(CmsContext))]
  partial class CmsContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "8.0.3")
          .HasAnnotation("Relational:MaxIdentifierLength", 128);

      SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

      modelBuilder.Entity("Logitar.Cms.EntityFrameworkCore.Entities.ArchetypeEntity", b =>
          {
            b.Property<int>("ArchetypeId")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArchetypeId"));

            b.Property<string>("AggregateId")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("nvarchar(255)");

            b.Property<string>("CreatedBy")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("nvarchar(255)");

            b.Property<DateTime>("CreatedOn")
                      .HasColumnType("datetime2");

            b.Property<string>("Description")
                      .HasColumnType("nvarchar(max)");

            b.Property<string>("DisplayName")
                      .HasMaxLength(255)
                      .HasColumnType("nvarchar(255)");

            b.Property<bool>("IsInvariant")
                      .HasColumnType("bit");

            b.Property<string>("UniqueName")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("nvarchar(255)");

            b.Property<string>("UniqueNameNormalized")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("nvarchar(255)");

            b.Property<string>("UpdatedBy")
                      .IsRequired()
                      .HasMaxLength(255)
                      .HasColumnType("nvarchar(255)");

            b.Property<DateTime>("UpdatedOn")
                      .HasColumnType("datetime2");

            b.Property<long>("Version")
                      .HasColumnType("bigint");

            b.HasKey("ArchetypeId");

            b.HasIndex("AggregateId")
                      .IsUnique();

            b.HasIndex("CreatedBy");

            b.HasIndex("CreatedOn");

            b.HasIndex("DisplayName");

            b.HasIndex("IsInvariant");

            b.HasIndex("UniqueName");

            b.HasIndex("UniqueNameNormalized")
                      .IsUnique();

            b.HasIndex("UpdatedBy");

            b.HasIndex("UpdatedOn");

            b.HasIndex("Version");

            b.ToTable("Archetypes", (string)null);
          });
#pragma warning restore 612, 618
    }
  }
}
