// <auto-generated />
using Logitar.Cms.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logitar.Cms.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(CmsContext))]
    [Migration("20250128023410_Cms_Release_1_0_0")]
    partial class Cms_Release_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentEntity", b =>
                {
                    b.Property<int>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentId"));

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ContentId");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Contents", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentLocaleEntity", b =>
                {
                    b.Property<int>("ContentLocaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentLocaleId"));

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FieldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PublishedRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ContentLocaleId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("IsPublished");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("PublishedOn");

                    b.HasIndex("PublishedRevision");

                    b.HasIndex("Revision");

                    b.HasIndex("UniqueName");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("ContentId", "LanguageId")
                        .IsUnique()
                        .HasFilter("[LanguageId] IS NOT NULL");

                    b.HasIndex("ContentTypeId", "LanguageId", "UniqueNameNormalized")
                        .IsUnique()
                        .HasFilter("[LanguageId] IS NOT NULL");

                    b.ToTable("ContentLocales", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", b =>
                {
                    b.Property<int>("ContentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContentTypeId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FieldCount")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInvariant")
                        .HasColumnType("bit");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ContentTypeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("FieldCount");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsInvariant");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("ContentTypes", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.FieldDefinitionEntity", b =>
                {
                    b.Property<int>("FieldDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldDefinitionId"));

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsIndexed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvariant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FieldDefinitionId");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("ContentTypeId", "Id")
                        .IsUnique();

                    b.HasIndex("ContentTypeId", "Order")
                        .IsUnique();

                    b.HasIndex("ContentTypeId", "UniqueNameNormalized")
                        .IsUnique();

                    b.ToTable("FieldDefinitions", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.FieldIndexEntity", b =>
                {
                    b.Property<int>("FieldIndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldIndexId"));

                    b.Property<bool?>("Boolean")
                        .HasColumnType("bit");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("ContentLocaleId")
                        .HasColumnType("int");

                    b.Property<string>("ContentLocaleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ContentTypeUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("FieldDefinitionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FieldDefinitionUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FieldTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FieldTypeUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<bool>("LanguageIsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LanguageUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Number")
                        .HasColumnType("float");

                    b.Property<string>("RelatedContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("RichText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Select")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("String")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldIndexId");

                    b.HasIndex("Boolean");

                    b.HasIndex("ContentId");

                    b.HasIndex("ContentLocaleId");

                    b.HasIndex("ContentLocaleName");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("ContentTypeName");

                    b.HasIndex("ContentTypeUid");

                    b.HasIndex("ContentUid");

                    b.HasIndex("DateTime");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("FieldDefinitionName");

                    b.HasIndex("FieldDefinitionUid");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("FieldTypeName");

                    b.HasIndex("FieldTypeUid");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageIsDefault");

                    b.HasIndex("LanguageUid");

                    b.HasIndex("Number");

                    b.HasIndex("Revision");

                    b.HasIndex("Status");

                    b.HasIndex("String");

                    b.HasIndex("ContentLocaleId", "FieldDefinitionId", "Status")
                        .IsUnique();

                    b.ToTable("FieldIndex", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.FieldTypeEntity", b =>
                {
                    b.Property<int>("FieldTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldTypeId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("FieldTypeId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DataType");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("FieldTypes", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.LanguageEntity", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CodeNormalized")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("LCID")
                        .HasColumnType("int");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StreamId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("LanguageId");

                    b.HasIndex("Code");

                    b.HasIndex("CodeNormalized")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("DisplayName");

                    b.HasIndex("EnglishName");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("IsDefault");

                    b.HasIndex("LCID");

                    b.HasIndex("NativeName");

                    b.HasIndex("StreamId")
                        .IsUnique();

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.PublishedContentEntity", b =>
                {
                    b.Property<int>("ContentLocaleId")
                        .HasColumnType("int");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ContentTypeUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FieldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<bool>("LanguageIsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LanguageUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UniqueNameNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ContentLocaleId");

                    b.HasIndex("ContentId");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("ContentTypeName");

                    b.HasIndex("ContentTypeUid");

                    b.HasIndex("ContentUid");

                    b.HasIndex("DisplayName");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageIsDefault");

                    b.HasIndex("LanguageUid");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("PublishedOn");

                    b.HasIndex("Revision");

                    b.HasIndex("UniqueName");

                    b.HasIndex("UniqueNameNormalized");

                    b.ToTable("PublishedContents", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.UniqueIndexEntity", b =>
                {
                    b.Property<int>("UniqueIndexId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniqueIndexId"));

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("ContentLocaleId")
                        .HasColumnType("int");

                    b.Property<string>("ContentLocaleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ContentTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ContentTypeUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FieldDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("FieldDefinitionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FieldDefinitionUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FieldTypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("FieldTypeUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(278)
                        .HasColumnType("nvarchar(278)");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<bool>("LanguageIsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LanguageUid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ValueNormalized")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UniqueIndexId");

                    b.HasIndex("ContentId");

                    b.HasIndex("ContentLocaleId");

                    b.HasIndex("ContentLocaleName");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("ContentTypeName");

                    b.HasIndex("ContentTypeUid");

                    b.HasIndex("ContentUid");

                    b.HasIndex("FieldDefinitionId");

                    b.HasIndex("FieldDefinitionName");

                    b.HasIndex("FieldDefinitionUid");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("FieldTypeName");

                    b.HasIndex("FieldTypeUid");

                    b.HasIndex("Key");

                    b.HasIndex("LanguageCode");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LanguageIsDefault");

                    b.HasIndex("LanguageUid");

                    b.HasIndex("Revision");

                    b.HasIndex("Status");

                    b.HasIndex("Value");

                    b.HasIndex("ValueNormalized");

                    b.HasIndex("FieldDefinitionId", "LanguageId", "Status", "ValueNormalized")
                        .IsUnique()
                        .HasFilter("[LanguageId] IS NOT NULL");

                    b.ToTable("UniqueIndex", (string)null);
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentEntity", b =>
                {
                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("Contents")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentLocaleEntity", b =>
                {
                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentEntity", "Content")
                        .WithMany("Locales")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("ContentLocales")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.LanguageEntity", "Language")
                        .WithMany("ContentLocales")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("ContentType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.FieldDefinitionEntity", b =>
                {
                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("Fields")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.FieldTypeEntity", "FieldType")
                        .WithMany("FieldDefinitions")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.FieldIndexEntity", b =>
                {
                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentEntity", "Content")
                        .WithMany("FieldIndex")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentLocaleEntity", "ContentLocale")
                        .WithMany("FieldIndex")
                        .HasForeignKey("ContentLocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("FieldIndex")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.FieldDefinitionEntity", "FieldDefinition")
                        .WithMany("FieldIndex")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.FieldTypeEntity", "FieldType")
                        .WithMany("FieldIndex")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.LanguageEntity", "Language")
                        .WithMany("FieldIndex")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Content");

                    b.Navigation("ContentLocale");

                    b.Navigation("ContentType");

                    b.Navigation("FieldDefinition");

                    b.Navigation("FieldType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.PublishedContentEntity", b =>
                {
                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentEntity", "Content")
                        .WithMany("PublishedContents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentLocaleEntity", "ContentLocale")
                        .WithOne("PublishedContent")
                        .HasForeignKey("Logitar.Cms.Infrastructure.Entities.PublishedContentEntity", "ContentLocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("PublishedContents")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.LanguageEntity", "Language")
                        .WithMany("PublishedContents")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Content");

                    b.Navigation("ContentLocale");

                    b.Navigation("ContentType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.UniqueIndexEntity", b =>
                {
                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentEntity", "Content")
                        .WithMany("UniqueIndex")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentLocaleEntity", "ContentLocale")
                        .WithMany("UniqueIndex")
                        .HasForeignKey("ContentLocaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("UniqueIndex")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.FieldDefinitionEntity", "FieldDefinition")
                        .WithMany("UniqueIndex")
                        .HasForeignKey("FieldDefinitionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.FieldTypeEntity", "FieldType")
                        .WithMany("UniqueIndex")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logitar.Cms.Infrastructure.Entities.LanguageEntity", "Language")
                        .WithMany("UniqueIndex")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Content");

                    b.Navigation("ContentLocale");

                    b.Navigation("ContentType");

                    b.Navigation("FieldDefinition");

                    b.Navigation("FieldType");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentEntity", b =>
                {
                    b.Navigation("FieldIndex");

                    b.Navigation("Locales");

                    b.Navigation("PublishedContents");

                    b.Navigation("UniqueIndex");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentLocaleEntity", b =>
                {
                    b.Navigation("FieldIndex");

                    b.Navigation("PublishedContent");

                    b.Navigation("UniqueIndex");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.ContentTypeEntity", b =>
                {
                    b.Navigation("ContentLocales");

                    b.Navigation("Contents");

                    b.Navigation("FieldIndex");

                    b.Navigation("Fields");

                    b.Navigation("PublishedContents");

                    b.Navigation("UniqueIndex");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.FieldDefinitionEntity", b =>
                {
                    b.Navigation("FieldIndex");

                    b.Navigation("UniqueIndex");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.FieldTypeEntity", b =>
                {
                    b.Navigation("FieldDefinitions");

                    b.Navigation("FieldIndex");

                    b.Navigation("UniqueIndex");
                });

            modelBuilder.Entity("Logitar.Cms.Infrastructure.Entities.LanguageEntity", b =>
                {
                    b.Navigation("ContentLocales");

                    b.Navigation("FieldIndex");

                    b.Navigation("PublishedContents");

                    b.Navigation("UniqueIndex");
                });
#pragma warning restore 612, 618
        }
    }
}
