name: Pull Request Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  lint-build:
    name: It lints and builds
    runs-on: ubuntu-latest

    steps:
      - name: Print current working directory
        run: echo "Current directory: ${{ github.workspace }}"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Clone CMS repository
        uses: actions/checkout@v2

      - name: Clone logitar-ui repository
        run: git clone https://github.com/Logitar/logitar-ui

      - name: Install dependencies (CMS)
        run: npm ci
        working-directory: CMS/src/Logitar.Cms.Ui

      - name: Install dependencies (logitar-ui)
        run: npm ci
        working-directory: logitar-ui

      - name: Link logitar-ui
        run: npm link
        working-directory: logitar-ui

      - name: Link logitar-ui in CMS
        run: npm link @logitar/logitar-ui
        working-directory: CMS/src/Logitar.Cms.Ui

      - name: Lint CMS/src/Logitar.Cms.Ui
        run: npm run lint
        working-directory: CMS/src/Logitar.Cms.Ui

      - name: Build CMS/src/Logitar.Cms.Ui
        run: npm run build
        working-directory: CMS/src/Logitar.Cms.Ui
