name: Frontend

on:
  pull_request:
    branches: [dev]

jobs:
  test:
    name: It lints and builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          cd ./src/Logitar.Cms.Ui
          npm i
          npm run lint
          npm run build
